/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yam.kakfa.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Photo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6245816492077294092L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Photo\",\"namespace\":\"com.yam.kakfa.avro\",\"fields\":[{\"name\":\"photoName\",\"type\":\"string\"},{\"name\":\"photoId\",\"type\":\"string\"},{\"name\":\"photoService\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Photo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Photo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Photo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Photo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Photo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Photo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Photo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Photo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Photo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence photoName;
  private java.lang.CharSequence photoId;
  private java.lang.CharSequence photoService;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Photo() {}

  /**
   * All-args constructor.
   * @param photoName The new value for photoName
   * @param photoId The new value for photoId
   * @param photoService The new value for photoService
   */
  public Photo(java.lang.CharSequence photoName, java.lang.CharSequence photoId, java.lang.CharSequence photoService) {
    this.photoName = photoName;
    this.photoId = photoId;
    this.photoService = photoService;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return photoName;
    case 1: return photoId;
    case 2: return photoService;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: photoName = (java.lang.CharSequence)value$; break;
    case 1: photoId = (java.lang.CharSequence)value$; break;
    case 2: photoService = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'photoName' field.
   * @return The value of the 'photoName' field.
   */
  public java.lang.CharSequence getPhotoName() {
    return photoName;
  }


  /**
   * Sets the value of the 'photoName' field.
   * @param value the value to set.
   */
  public void setPhotoName(java.lang.CharSequence value) {
    this.photoName = value;
  }

  /**
   * Gets the value of the 'photoId' field.
   * @return The value of the 'photoId' field.
   */
  public java.lang.CharSequence getPhotoId() {
    return photoId;
  }


  /**
   * Sets the value of the 'photoId' field.
   * @param value the value to set.
   */
  public void setPhotoId(java.lang.CharSequence value) {
    this.photoId = value;
  }

  /**
   * Gets the value of the 'photoService' field.
   * @return The value of the 'photoService' field.
   */
  public java.lang.CharSequence getPhotoService() {
    return photoService;
  }


  /**
   * Sets the value of the 'photoService' field.
   * @param value the value to set.
   */
  public void setPhotoService(java.lang.CharSequence value) {
    this.photoService = value;
  }

  /**
   * Creates a new Photo RecordBuilder.
   * @return A new Photo RecordBuilder
   */
  public static com.yam.kakfa.avro.Photo.Builder newBuilder() {
    return new com.yam.kakfa.avro.Photo.Builder();
  }

  /**
   * Creates a new Photo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Photo RecordBuilder
   */
  public static com.yam.kakfa.avro.Photo.Builder newBuilder(com.yam.kakfa.avro.Photo.Builder other) {
    if (other == null) {
      return new com.yam.kakfa.avro.Photo.Builder();
    } else {
      return new com.yam.kakfa.avro.Photo.Builder(other);
    }
  }

  /**
   * Creates a new Photo RecordBuilder by copying an existing Photo instance.
   * @param other The existing instance to copy.
   * @return A new Photo RecordBuilder
   */
  public static com.yam.kakfa.avro.Photo.Builder newBuilder(com.yam.kakfa.avro.Photo other) {
    if (other == null) {
      return new com.yam.kakfa.avro.Photo.Builder();
    } else {
      return new com.yam.kakfa.avro.Photo.Builder(other);
    }
  }

  /**
   * RecordBuilder for Photo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Photo>
    implements org.apache.avro.data.RecordBuilder<Photo> {

    private java.lang.CharSequence photoName;
    private java.lang.CharSequence photoId;
    private java.lang.CharSequence photoService;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yam.kakfa.avro.Photo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.photoName)) {
        this.photoName = data().deepCopy(fields()[0].schema(), other.photoName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.photoId)) {
        this.photoId = data().deepCopy(fields()[1].schema(), other.photoId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.photoService)) {
        this.photoService = data().deepCopy(fields()[2].schema(), other.photoService);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Photo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yam.kakfa.avro.Photo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.photoName)) {
        this.photoName = data().deepCopy(fields()[0].schema(), other.photoName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.photoId)) {
        this.photoId = data().deepCopy(fields()[1].schema(), other.photoId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.photoService)) {
        this.photoService = data().deepCopy(fields()[2].schema(), other.photoService);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'photoName' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhotoName() {
      return photoName;
    }


    /**
      * Sets the value of the 'photoName' field.
      * @param value The value of 'photoName'.
      * @return This builder.
      */
    public com.yam.kakfa.avro.Photo.Builder setPhotoName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.photoName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'photoName' field has been set.
      * @return True if the 'photoName' field has been set, false otherwise.
      */
    public boolean hasPhotoName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'photoName' field.
      * @return This builder.
      */
    public com.yam.kakfa.avro.Photo.Builder clearPhotoName() {
      photoName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'photoId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhotoId() {
      return photoId;
    }


    /**
      * Sets the value of the 'photoId' field.
      * @param value The value of 'photoId'.
      * @return This builder.
      */
    public com.yam.kakfa.avro.Photo.Builder setPhotoId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.photoId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'photoId' field has been set.
      * @return True if the 'photoId' field has been set, false otherwise.
      */
    public boolean hasPhotoId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'photoId' field.
      * @return This builder.
      */
    public com.yam.kakfa.avro.Photo.Builder clearPhotoId() {
      photoId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'photoService' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhotoService() {
      return photoService;
    }


    /**
      * Sets the value of the 'photoService' field.
      * @param value The value of 'photoService'.
      * @return This builder.
      */
    public com.yam.kakfa.avro.Photo.Builder setPhotoService(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.photoService = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'photoService' field has been set.
      * @return True if the 'photoService' field has been set, false otherwise.
      */
    public boolean hasPhotoService() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'photoService' field.
      * @return This builder.
      */
    public com.yam.kakfa.avro.Photo.Builder clearPhotoService() {
      photoService = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Photo build() {
      try {
        Photo record = new Photo();
        record.photoName = fieldSetFlags()[0] ? this.photoName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.photoId = fieldSetFlags()[1] ? this.photoId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.photoService = fieldSetFlags()[2] ? this.photoService : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Photo>
    WRITER$ = (org.apache.avro.io.DatumWriter<Photo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Photo>
    READER$ = (org.apache.avro.io.DatumReader<Photo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.photoName);

    out.writeString(this.photoId);

    out.writeString(this.photoService);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.photoName = in.readString(this.photoName instanceof Utf8 ? (Utf8)this.photoName : null);

      this.photoId = in.readString(this.photoId instanceof Utf8 ? (Utf8)this.photoId : null);

      this.photoService = in.readString(this.photoService instanceof Utf8 ? (Utf8)this.photoService : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.photoName = in.readString(this.photoName instanceof Utf8 ? (Utf8)this.photoName : null);
          break;

        case 1:
          this.photoId = in.readString(this.photoId instanceof Utf8 ? (Utf8)this.photoId : null);
          break;

        case 2:
          this.photoService = in.readString(this.photoService instanceof Utf8 ? (Utf8)this.photoService : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (photoName == null ? 0 : photoName.hashCode());
    result = 31 * result + (photoId == null ? 0 : photoId.hashCode());
    result = 31 * result + (photoService == null ? 0 : photoService.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Photo)) {
      return false;
    }
    Photo other = (Photo) o;
    if (Utf8.compareSequences(this.photoName, other.photoName) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.photoId, other.photoId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.photoService, other.photoService) != 0) {
      return false;
    }
    return true;
  }
}










